# --- SEPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

# update the target network every {} training steps
target_update_interval_or_tau: 0.01


lr: 0.0003

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# use IPPO
agent_output_type: "pi_logits"
learner: "seppo_learner"
entropy_coef: 0.01
standardise_returns: False
standardise_rewards: True
use_rnn: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic_es"
epochs: 4
eps_clip: 0.2
name: "seppo"

t_max: 20050000

mac: "exp_share_mac"
agent: "rnn_ns"
use_critic_importance_sampling: False # to add importance sampling weights on critic loss term
kl_logs: False # early stopping the training if kl_divergence go beyond kl_target
lambda_matrix: 'one' # 'one' for all one values (all sharing experience), 'diag' for only diagonal values (No experience sharing), 'selective' for selective experience sharing
lambda_select_method: 'cutoff' # 'cutoff' method
lambda_cutoff: 1.0 # KL div cutoff
lambda_update_interval: 10000
lambda_update_start: 50000

metric: 'kl' # 'kl' for KL divergence, 'js' for Jensen-Shannon distance